### PR TITLE
Added new aqua and indigo colors.

### PR DESCRIPTION
**Pull request by matthewgallo**
Added new aqua and indigo colors approved by the IBM Design Language team.

### CODE REVIEW

**Comment by Snugug** [comment]
Can you please point to these new colors in the official IBM Design color catalog so we can 2x check them? Thanks.

**Comment by matthewgallo** [comment]
Hey, I'm updating the public design language site with the new colors tomorrow. I worked with Stephanie Hagadorn and Hayley Hughes to get all of these colors correct and also have an internal url I can send to you with them added as well to the color catalog page.

**Comment by mbarlock** [comment]
That would be great sense I've had to fix out of date colors too many times...

**Comment by mbarlock** [comment]
Hmm, this is a great showing that I need I create the 2.0 release so we only need up update the json block rather than the language files as well.

**Comment by mbarlock** [comment]
Also, most importantly, super thrilled about new colors! 🎉

**Pull request merged**
